#!/usr/bin/env bash

# Copyright 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is derived from the following:
# https://github.com/openshift/must-gather/blob/release-4.21/collection-scripts/version

# This file comes from the original openshift must-gather image.
# This function was duplicated in case we want to change this logic later 
# and it allows us to run './gather_kuadrant' locally without having to build the image

function version() {
  if [[ -n $KUADRANT_MUSTGATHER_VERSION ]] ; then
    echo "${KUADRANT_MUSTGATHER_VERSION}"
  else
    echo "0.0.0-unknown"
  fi
}